
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SrHvGnKH7Vi9Wlp82TVZ7xGkJvdoy7o',
    appId: '1:1068560645570:android:e50e65a40870a000312a5b',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGHfZWWwXA_UD8B8-eYOVdxSYMr4qBTp0',
    appId: '1:1068560645570:ios:13c1a70abb412f1d312a5b',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
    iosBundleId: 'com.example.ubicate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgQdE_E_PkfumQ9__kTNGkzJ2r3aET6Ts',
    appId: '1:1068560645570:web:59dc7b3f9c7a30ad312a5b',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    authDomain: 'ubicate-4271d.firebaseapp.com',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGHfZWWwXA_UD8B8-eYOVdxSYMr4qBTp0',
    appId: '1:1068560645570:ios:13c1a70abb412f1d312a5b',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
    iosBundleId: 'com.example.ubicate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgQdE_E_PkfumQ9__kTNGkzJ2r3aET6Ts',
    appId: '1:1068560645570:web:7e8b58d396d8390e312a5b',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    authDomain: 'ubicate-4271d.firebaseapp.com',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
  );

}