// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SrHvGnKH7Vi9Wlp82TVZ7xGkJvdoy7o',
    appId: '1:1068560645570:android:e50e65a40870a000312a5b',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6SrHvGnKH7Vi9Wlp82TVZ7xGkJvdoy7o',
    appId: '1:1068560645570:ios:PLACEHOLDER',
    messagingSenderId: '1068560645570',
    projectId: 'ubicate-4271d',
    databaseURL: 'https://ubicate-4271d-default-rtdb.firebaseio.com',
    storageBucket: 'ubicate-4271d.firebasestorage.app',
    iosBundleId: 'com.example.ubicate',
  );
}
